backend:
  name: git-gateway
  branch: main

  commit_messages:
    create: ':pencil: Create {{collection}} “{{slug}}”'
    update: ':pencil: Update {{collection}} “{{slug}}”'
    delete: ':fire: Delete {{collection}} “{{slug}}”'
    uploadMedia: ':bento: Upload “{{path}}” [skip ci]'
    deleteMedia: ':fire: Delete “{{path}}” [skip ci]'

media_folder: content/assets
public_folder: /assets
locale: pt
display_url: https://dsoares.me
logo_url: https://dsoares.me/logo.svg

collections:
  - name: posts
    label: Posts
    label_singular: post
    folder: content/blog
    create: true
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    fields:
      - {
          label: templateKey,
          name: templateKey,
          widget: hidden,
          default: blog-post,
        }
      - { label: Título, name: title, widget: string }
      - {
          label: Data,
          name: date,
          widget: datetime,
          format: YYYY-MM-DD HH:mm:ss,
        }
      - { label: Imagem em destaque, name: image, widget: image }
      - { label: Tags, name: tags, widget: string }
      - { label: Descrição, name: description, widget: text }
      - { label: Corpo, name: body, widget: markdown }

  - name: settings
    label: Settings
    media_folder: ''
    public_folder: ''
    sortable_fields: []
    editor:
      preview: false
    files:
      - file: README.md
        label: Leia me
        name: readme
        fields:
          - { label: Body, name: body, widget: markdown }

      - file: content/settings/siteMetadata.json
        label: Metadata
        name: siteMetadata
        fields:
          - { label: Título, name: title, widget: string }
          - { label: Título curto, name: shortTitle, widget: string }
          - { label: Descrição, name: description, widget: text }
          - { label: URL do site, name: siteUrl, widget: string }
          - { label: Favicon, name: favicon, widget: image }
          - { label: Lang, name: lang, widget: string }
          - { label: GTM ID, name: gtmID, widget: string }
          - label: Links sociais
            label_singular: profile
            name: socialLinks
            widget: list
            fields:
              - {
                  label: Links sociais,
                  name: label,
                  widget: select,
                  options:
                    [
                      Behance,
                      Dribbble,
                      Email,
                      Facebook,
                      Github,
                      Instagram,
                      Medium,
                      Messenger,
                      Telegram,
                      Twitter,
                      WhatsApp,
                    ],
                }

              - { label: URL, name: url, widget: string }
