backend:
  name: github
  repo: dsoaress/dsoares.me
  branch: master

  commit_messages:
    create: ":sparkles: {{slug}}"
    update: ":speech_balloon: {{slug}}"
    delete: ":fire: {{slug}}"
    uploadMedia: "[skip ci] :bento: {{path}}"
    deleteMedia: "[skip ci] :fire: {{path}}"

media_folder: "static/images"
public_folder: "images"

locale: "pt"

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "blogPost"

      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Data"
        name: "date"
        widget: "datetime"
        dateFormat: "DD/MM/YYYY"
        timeFormat: "HH:mm"
        format: "YYYY-MM-DD HH:mm:ss"

      - label: "Tags"
        name: "tags"
        widget: "list"

      - label: "Texto"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Páginas"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "indexPage"

          - label: "Título"
            name: "title"
            widget: "hidden"
            default: "Home"

          - label: "Saudação"
            name: "greeting"
            widget: "string"

          - label: "Texto"
            name: "body"
            widget: "markdown"
