name: Check PR

on: [pull_request]

jobs:
  run-ci:
    name: Run Type Check & Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@HEAD

      - name: Check types
        run: yarn type-check

      - name: Jest
        run: yarn test:ci

      - name: Check linting
        run: yarn test:lint
