name: Test and merge
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install && npm i -g gatsby-cli

      - name: Build
        run: gatsby build

  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: pascalgn/automerge-action@v0.11.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
          MERGE_METHOD: 'squash'
          MERGE_FORKS: 'false'
          UPDATE_LABELS: ''
          MERGE_DELETE_BRANCH: 'true'
          UPDATE_METHOD: 'merge'
