name: Checks

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

  check-types:
    name: Check types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            _data
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run type-check
        run: yarn type-check

  check-linters:
    name: Check linters
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            _data
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run test:lint
        run: yarn test:lint

  testing:
    name: Jest
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            _data
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run tests and collect coverage
        run: yarn test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
